<?php
$hex_data = new stdClass;

$hex_data->chars_arr = [
"&Omega;","䷁","䷀","䷂","䷃","䷄","䷅","䷆","䷇","䷈","䷉","䷊","䷋","䷌","䷍","䷎","䷏","䷐","䷑","䷒","䷓","䷔","䷕",
"䷖","䷗","䷘","䷙","䷚","䷛","䷜","䷝","䷞","䷟","䷠","䷡","䷢","䷣","䷤","䷥","䷦","䷧","䷨","䷩","䷪","䷫","䷬",
"䷭","䷮","䷯","䷰","䷱","䷲","䷳","䷴","䷵","䷶","䷷","䷸","䷹","䷺","䷻","䷼","䷽","䷾","䷿"
];

$hex_data->names_arr = [
                "error",
                "Field | The Receptive | 'Yin'",
                "Force | The Creative | 'Yang'",
                "Sprouting | Initial Difficulty | 'Birth'",
                "Enveloping | Youthful Folly | 'The Novice'",
                "Attending | Waiting | 'Waiting'",
                "Arguing | Conflict | 'Balance'",
                "Leading | The Army | 'The Gathering'",
                "Grouping | Holding Together | 'Merging'",
                "Small Accumulating | Small Taming | 'Reticence'",
                "Treading | Conduct | 'Humility'",
                "Pervading | Peace | 'Harmony'",
                "Obstruction | Standstill | 'Trust'",
                "Concordance | Fellowship | 'community'",
                "Great Possession | Great Possession | 'Prosperity'",
                "Humbling | Modesty | 'The Guileless'",
                "Providing-For | Enthusiasm | 'Music'",
                "Following | Following | 'Accord'",
                "Corrupting | Work on the Decayed | 'Repair'",
                "Nearing | Approach | 'Quickening'",
                "Viewing | Contemplation -'Reflection'",
                "Gnawing Bite | Biting Through | 'Perseverence'",
                "Adorning | Grace | 'Grace'",
                "Stripping | Spitting Apart | 'Dismantling'",
                "Returning | Return | 'Genesis'",
                "Without Embroiling | Innocence | 'The Child'",
                "Great Accumulating | Great Taming | 'Composure'",
                "Swallowing | Nourishment | 'Sustenance'",
                "Great Exceeding | Great Preponderance | 'Potential'",
                "Gorge | The Abyss | 'Danger'",
                "Radiance | The Clinging | 'Synergy'",
                "Conjoining | Influence | 'Allurement'",
                "Persevering | Duration | 'Continuity'",
                "Retiring | Retreat | 'Rest'",
                "Great Invigorating | Great Power | 'Leadership'",
                "Prospering | Progress | 'Progress'",
                "Brightness Hiding | Darkening | 'Submission'",
                "Dwelling People | The Family | 'The Whole'",
                "Polarising | Opposition | 'Opposites'",
                "Limping--Obstruction | 'The Web'",
                "Taking Apart | Deliverance | 'Release'",
                "Diminishing | Decrease | 'Austerity'",
                "Augmenting | Increase | 'Generosity'",
                "Parting | Breakthrough | 'Transformation'",
                "Coupling | Coming to Meet | 'Encounter'",
                "Clustering | Gathering Together | 'Weaving'",
                "Ascending | Pushing Upward | 'Tenacity'",
                "Confining | Oppression | 'Acceptance'",
                "Welling | The Well | 'The Well'",
                "Skinning | Revolution | 'Revolution'",
                "Holding | The Cauldron | 'Peace'",
                "Shake | Arousing | 'Initiation'",
                "Bound | The Keeping Still | 'Stillness'",
                "Infiltratiing | Development | 'Unfolding'",
                "Converting the Maiden | Marrying | 'Submission'",
                "Abounding | Abundance | 'The Peak'",
                "Sojourning | The Wanderer | 'The Wanderer'",
                "Ground | The Gentle | 'Alchemy'",
                "Open | The Joyous | 'Joy'",
                "Dispersing | Dispersion | 'Detachment'",
                "Articulating | Limitation | 'Boundaries'",
                "Center Confirming | Inner Truth | 'Empathy'",
                "Small Exceeding | Small Preponderance | 'Diligence'",
                "Already Fording | After Completion | 'Being'",
                "Not-Yet-Fording | Before Completion | 'Becoming'"

];
?>
